### ISSUE TITLE
Cluster mode #scan is not working properly

### ISSUE THREAD

**Issue by estepnv** [redis/redis-rb#1045]
redis (4.5.1)

I assume that KEYS * resulting set must be equal to the sum of SCAN X MATCH * calls

Currently when connected to in Redis cluster mode `Redis#scan` and `Redis#scan_each` does not conform to the rule above.

According to https://github.com/redis/redis-rb/blob/master/lib/redis/cluster.rb#L130
`Redis::Cluster#send_command` will execute `#scan_each` on a random node, however, IMO it has to iterate over all nodes and collect data from them.

If anybody helps me with local setup (docker-compose file) I'll try to implement this with tests

**Comment by supercaracal** [comment]
Example of Docker Compose:

```yaml
version: '3.9'
services:
  node1: &node
    image: "redis:6.2.6"
    command: >
      redis-server --maxmemory            64mb
                   --maxmemory-policy     allkeys-lru
                   --appendonly           yes
                   --cluster-enabled      yes
                   --cluster-config-file  nodes.conf
                   --cluster-node-timeout 5000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: '3s'
      timeout: '1s'
      retries: 10
    ports:
      - "7000:6379"
  node2:
    <<: *node
    ports:
      - "7001:6379"
  node3:
    <<: *node
    ports:
      - "7002:6379"
  node4:
    <<: *node
    ports:
      - "7003:6379"
  node5:
    <<: *node
    ports:
      - "7004:6379"
  node6:
    <<: *node
    ports:
      - "7005:6379"
  node-redis-cluster:
    image: "redis:6.2.6"
    command: >
      bash -c "apt-get update
      && apt-get install --no-install-recommends --no-install-suggests -y dnsutils
      && yes yes | redis-cli --cluster create
      $$(dig node1 +short):6379
      $$(dig node2 +short):6379
      $$(dig node3 +short):6379
      $$(dig node4 +short):6379
      $$(dig node5 +short):6379
      $$(dig node6 +short):6379
      --cluster-replicas 1"
    depends_on:
      node1:
        condition: service_healthy
      node2:
        condition: service_healthy
      node3:
        condition: service_healthy
      node4:
        condition: service_healthy
      node5:
        condition: service_healthy
      node6:
        condition: service_healthy
```

```
$ docker-compose ps
           Name                         Command                  State                        Ports
---------------------------------------------------------------------------------------------------------------------
redis_node-redis-cluster_1   docker-entrypoint.sh bash  ...   Exit 0
redis_node1_1                docker-entrypoint.sh redis ...   Up (healthy)   0.0.0.0:7000->6379/tcp,:::7000->6379/tcp
redis_node2_1                docker-entrypoint.sh redis ...   Up (healthy)   0.0.0.0:7001->6379/tcp,:::7001->6379/tcp
redis_node3_1                docker-entrypoint.sh redis ...   Up (healthy)   0.0.0.0:7002->6379/tcp,:::7002->6379/tcp
redis_node4_1                docker-entrypoint.sh redis ...   Up (healthy)   0.0.0.0:7003->6379/tcp,:::7003->6379/tcp
redis_node5_1                docker-entrypoint.sh redis ...   Up (healthy)   0.0.0.0:7004->6379/tcp,:::7004->6379/tcp
redis_node6_1                docker-entrypoint.sh redis ...   Up (healthy)   0.0.0.0:7005->6379/tcp,:::7005->6379/tcp
```
