### ISSUE TITLE
How does redis-rb address clustering issues when the cluster is configured with addresses that are inaccessible by the machine running the redis client?

### ISSUE THREAD

**Issue by alilland** [redis/redis-rb#1112]
I am building out a development environment on my macos with docker, but I ran into a snag that I'm not sure how to get around.

I have a redis cluster running on my MacOS using the default utility scripts that come with redis found at `redis-6.2.6/utils/create-cluster/create-cluster start`

by default this runs on `127.0.0.1` and spins up 6 nodes (3 master 3 slave)
```
Starting 30001
Starting 30002
Starting 30003
Starting 30004
Starting 30005
Starting 30006
```

my issue seems to be with topology, the cluster is configured with `127.0.0.1` and it'll not be accessible from the server side using `127.0.0.1`, within the docker container you must use `host.docker.internal` to reach the host's localhost environment

```ruby
connection = Redis.new(
  cluster: [
    "redis://host.docker.internal:30001",
    "redis://host.docker.internal:30002",
    "redis://host.docker.internal:30003"
  ],
  replica: true
)
```

the nodejs redis library seems to provide a [Node Address Map ](https://github.com/redis/node-redis/blob/master/docs/clustering.md#node-address-map) where you can tell your app what localhost address maps to the docker dns lookup - but im not sure how to do this in ruby. There was no documentation available in ruby, originally i got it working OUTSIDE of docker and just on my normal OS by reading tests that were written [here](https://github.com/redis/redis-rb/blob/5fb64bdecacac0bc5738f194ab82cd1001071879/test/cluster_client_options_test.rb).

But i'm not sure what i'll have to do to get this working with docker

**Comment by supercaracal** [comment]
The `fixed_hostname` option might be useful in that case:

```ruby
connection = Redis.new(
  cluster: [
    "redis://host.docker.internal:30001",
    "redis://host.docker.internal:30002",
    "redis://host.docker.internal:30003"
  ],
  replica: true,
  fixed_hostname: "host.docker.internal"
)
```

Also, in my local environment with WSL2, I prefer to use the client with Docker Compose like this:

```yaml
services:
  node1: &node
    image: "redis:${REDIS_VERSION:-7}"
    command: >
      redis-server
      --maxmemory            64mb
      --maxmemory-policy     allkeys-lru
      --appendonly           yes
      --cluster-enabled      yes
      --cluster-config-file  nodes.conf
      --cluster-node-timeout 5000
    restart: "${RESTART_POLICY:-always}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: "7s"
      timeout: "5s"
      retries: 10
    ports:
      - "6379:6379"
  node2:
    <<: *node
    ports:
      - "6380:6379"
  node3:
    <<: *node
    ports:
      - "6381:6379"
  node4:
    <<: *node
    ports:
      - "6382:6379"
  node5:
    <<: *node
    ports:
      - "6383:6379"
  node6:
    <<: *node
    ports:
      - "6384:6379"
  clustering:
    image: "redis:${REDIS_VERSION:-7}"
    command: >
      bash -c "apt-get update > /dev/null
      && apt-get install --no-install-recommends --no-install-suggests -y dnsutils > /dev/null
      && rm -rf /var/lib/apt/lists/*
      && yes yes | redis-cli --cluster create
      $$(dig node1 +short):6379
      $$(dig node2 +short):6379
      $$(dig node3 +short):6379
      $$(dig node4 +short):6379
      $$(dig node5 +short):6379
      $$(dig node6 +short):6379
      --cluster-replicas 1"
    depends_on:
      node1:
        condition: service_healthy
      node2:
        condition: service_healthy
      node3:
        condition: service_healthy
      node4:
        condition: service_healthy
      node5:
        condition: service_healthy
      node6:
        condition: service_healthy
```

```ruby
# On a Ruby application container in the same network
Redis.new(cluster: %w[redis://node1:6379], replica: true)

# On localhost
Redis.new(cluster: %w[redis://127.0.0.1:6379], replica: true)
```

But I don't know whether it works on MacOS or not.

https://github.com/redis/redis/blob/33bd8fb9810249a35d3bd9f5ddcb8a4f85a1c725/redis.conf#L1758-L1795
